version: "3.7"

services:
  sbot:
    build: .
    command: python -u /app/main.py >> /app/activity.log 2>&1
    privileged: true
    volumes:
      - .:/app
    container_name: sbot
    restart: always
